(()=>{'use strict';
const URL='https://plzktdfumurucbkwdhbu.supabase.co';
const KEY='sb_publishable_FSfGEy-i8R8LdQ-5OJwYtQ_MI6AUvVN';
const db=window.supabase?.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true}});
const app=document.getElementById('app');
const S={session:null,profile:null,route:'dashboard',q:'',page:1,size:10,date:new Date().toISOString().slice(0,10),classId:'',section:'',att:[]};
const esc=x=>String(x??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const initials=x=>String(x||'U').split(/\s+/).filter(Boolean).slice(0,2).map(v=>v[0]).join('').toUpperCase();
const toast=m=>{const r=document.getElementById('toast-root'),x=document.createElement('div');x.className='toast show';x.textContent=m;r.appendChild(x);setTimeout(()=>x.remove(),2600)};
const admin=()=>S.profile?.role==='admin';
const can=p=>admin()||S.profile?.permissions?.includes(p);
const nav=[['dashboard','Dashboard','⌂'],['students','Students','♙'],['teachers','Teachers','♟'],['classes','Classes','▦'],['attendance','Attendance','✓'],['reports','Reports','▥'],['users','Users','◎'],['logs','Activity Logs','◷'],['settings','Settings','⚙']];
function login(){app.innerHTML='<main class="login-page"><section class="login-card"><div class="brand-lockup"><img src="Screenshot_20260821-202536.png" alt="KITC"><div><strong>KITC Attendance</strong><span>Administration Console</span></div></div><h1>Welcome back</h1><p>Sign in to manage students, classes and attendance securely.</p><form id="loginForm"><div class="field"><label>Email address</label><input name="email" type="email" required autocomplete="username"></div><div class="field"><label>Password</label><input name="password" type="password" required minlength="6" autocomplete="current-password"></div><div id="loginError"></div><button class="btn btn-primary full" id="loginBtn">Sign in</button></form><p style="margin-top:18px;font-size:11px">Protected area. Role and permission checks are enforced at the data layer.</p></section></main>';document.getElementById('loginForm').onsubmit=signin}
async function signin(e){e.preventDefault();const f=new FormData(e.target),b=document.getElementById('loginBtn');b.disabled=true;b.textContent='Signing in…';const {error}=await db.auth.signInWithPassword({email:String(f.get('email')).trim(),password:String(f.get('password'))});if(error){document.getElementById('loginError').innerHTML='<div class="error-box">'+esc(error.message)+'</div>';b.disabled=false;b.textContent='Sign in';}}
async function boot(){if(!db)return login();const {data}=await db.auth.getSession();S.session=data.session;if(!S.session)return login();const {data:p,error}=await db.from('attendance_profiles').select('*').eq('id',S.session.user.id).single();if(error)throw error;S.profile=p;S.profile.permissions=admin()?['*']:(await db.from('attendance_role_permissions').select('permission').eq('role',p.role)).data?.map(x=>x.permission)||[];shell();go('dashboard')}
function shell(){app.innerHTML='<div class="mobile-overlay" id="overlay"></div><div class="app-layout"><aside class="sidebar" id="sidebar"><div class="sidebar-brand"><img src="Screenshot_20260821-202536.png" alt="KITC"><div><strong>KITC Attendance</strong><span>Admin Console</span></div></div><div class="nav-label">Workspace</div><nav class="nav">'+nav.map(([k,l,i])=>'<button class="nav-btn" data-route="'+k+'"><span class="nav-icon">'+i+'</span>'+l+'</button>').join('')+'</nav><div class="sidebar-footer"><div class="account-mini"><span class="avatar">'+initials(S.profile.full_name)+'</span><div><strong>'+esc(S.profile.full_name)+'</strong><span>'+esc(S.profile.role)+'</span></div></div><button class="nav-btn" id="logout"><span class="nav-icon">↪</span>Logout</button></div></aside><section class="main-shell"><header class="topbar"><button class="mobile-menu" id="menu">☰</button><div class="top-title" id="topTitle"></div><div class="top-search"><div class="searchbox"><span>⌕</span><input id="globalSearch" placeholder="Search students, teachers, classes…"></div></div><div class="top-actions"><button class="icon-btn">♢</button><span class="avatar">'+initials(S.profile.full_name)+'</span></div></header><main class="content" id="view"></main></section></div>';document.querySelectorAll('[data-route]').forEach(x=>x.onclick=()=>go(x.dataset.route));document.getElementById('logout').onclick=()=>db.auth.signOut();document.getElementById('menu').onclick=()=>{document.getElementById('sidebar').classList.toggle('open');document.getElementById('overlay').classList.toggle('show')};document.getElementById('overlay').onclick=()=>{document.getElementById('sidebar').classList.remove('open');document.getElementById('overlay').classList.remove('show')};document.getElementById('globalSearch').oninput=e=>{S.q=e.target.value;S.page=1;if(['students','teachers'].includes(S.route))entityPage(document.getElementById('view'),S.route)}}
function go(r){if(r==='users'&&!can('manage_users'))return toast('Users management is restricted');if(r==='reports'&&!can('view_reports'))return toast('Reports are restricted');S.route=r;S.page=1;document.querySelectorAll('[data-route]').forEach(x=>x.classList.toggle('active',x.dataset.route===r));document.getElementById('topTitle').textContent=nav.find(x=>x[0]===r)?.[1]||'Dashboard';const v=document.getElementById('view');v.innerHTML='<div class="loading">Loading…</div>';({dashboard,students:()=>entityPage(v,'students'),teachers:()=>entityPage(v,'teachers'),classes:()=>classesPage(v),attendance:()=>attendancePage(v),reports:()=>reportsPage(v),users:()=>usersPage(v),logs:()=>logsPage(v),settings:()=>settingsPage(v)}[r]||dashboard)(v).catch(e=>{console.error(e);v.innerHTML='<section class="panel"><div class="error-box">Unable to load this section: '+esc(e.message)+'</div><button class="btn btn-secondary" onclick="go(\''+r+'\')">Retry</button></section>'})}
const head=(ey,t,d,b='')=>'<div class="page-head"><div><div class="eyebrow">'+esc(ey)+'</div><h1>'+esc(t)+'</h1><p>'+esc(d)+'</p></div>'+b+'</div>';
async function dashboard(v){const today=S.date;const qs=await Promise.all(['attendance_students','attendance_teachers','attendance_classes'].map(t=>db.from(t).select('id',{count:'exact',head:true}).eq('status','active')));const rec=await db.from('attendance_records').select('status').eq('attendance_date',today);const rows=rec.data||[],p=rows.filter(x=>x.status==='present').length;const logs=await db.from('attendance_activity_logs').select('*').order('created_at',{ascending:false}).limit(7);v.innerHTML=head('Overview','Attendance dashboard','Daily attendance operations and system activity.','<button class="btn btn-primary" onclick="go(\'attendance\')">✓ Take attendance</button>')+'<section class="stats-grid"><article class="stat-card"><span class="stat-label">Total students</span><strong>'+qs[0].count+'</strong><span class="stat-meta">Active</span></article><article class="stat-card"><span class="stat-label">Total teachers</span><strong>'+qs[1].count+'</strong><span class="stat-meta">Active</span></article><article class="stat-card"><span class="stat-label">Total classes</span><strong>'+qs[2].count+'</strong><span class="stat-meta">Active</span></article><article class="stat-card"><span class="stat-label">Today rate</span><strong>'+(rows.length?Math.round(p/rows.length*100):0)+'%</strong><span class="stat-meta">'+p+' present / '+Math.max(rows.length-p,0)+' absent</span></article><article class="stat-card"><span class="stat-label">Records today</span><strong>'+rows.length+'</strong><span class="stat-meta">Attendance entries</span></article></section><div class="dashboard-grid"><section class="chart-card"><div class="panel-title"><h2>Attendance trend</h2><span>Last 7 days</span></div><div id="trend" class="trend-chart"><div class="loading">Loading trend…</div></div><div class="quick-actions"><button class="btn btn-secondary btn-sm" onclick="go(\'students\')">♙ Students</button><button class="btn btn-secondary btn-sm" onclick="go(\'classes\')">▦ Classes</button><button class="btn btn-secondary btn-sm" onclick="go(\'reports\')">▥ Reports</button></div></section><section class="activity-card"><div class="panel-title"><h2>Recent activity</h2><button class="btn btn-ghost btn-sm" onclick="go(\'logs\')">View all</button></div><div class="activity-list">'+((logs.data||[]).map(a=>'<div class="activity-item"><span class="activity-icon">✓</span><div><strong>'+esc(a.action)+'</strong><p>'+esc(a.target_type||'System')+'</p></div><span class="activity-time">'+timeAgo(a.created_at)+'</span></div>').join('')||'<div class="empty"><p>No activity recorded yet.</p></div>')+'</div></section></div>';trend()}
async function trend(){const el=document.getElementById('trend');if(!el)return;const a=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const day=d.toISOString().slice(0,10);const {data}=await db.from('attendance_records').select('status').eq('attendance_date',day);const all=data||[],p=all.filter(x=>x.status==='present').length;a.push({l:d.toLocaleDateString(undefined,{weekday:'short'}),p:all.length?Math.round(p/all.length*100):0})}el.innerHTML=a.map(x=>'<div class="bar-wrap"><div class="bar" style="height:'+Math.max(x.p,3)+'%"></div><span class="bar-label">'+x.l+'</span></div>').join('')}
const timeAgo=t=>{const m=Math.max(1,Math.round((Date.now()-new Date(t).getTime())/60000));return m<60?m+'m ago':m<1440?Math.round(m/60)+'h ago':new Date(t).toLocaleDateString()};
