(() => {
  const seed={members:[{name:'Anim Katwal',role:'Secretary',class:'Management',status:'Active'}],meetings:[],tasks:[],events:[],attendance:[],issues:[],documents:[]};
  const data=window.kitcData=window.kitcData||{};Object.keys(seed).forEach(k=>{if(!Array.isArray(data[k]))data[k]=JSON.parse(JSON.stringify(seed[k]))});
  const files={members:'members.json',meetings:'meetings.json',tasks:'tasks.json',events:'events.json',attendance:'attendance.json',issues:'issues.json',documents:'documents.json'};
  const modules={members:['♙','Members','Profiles, management roles, contact details and member history.'],meetings:['▣','Meetings','Agendas, attendees, minutes, decisions and follow-up tasks.'],tasks:['✓','Tasks','Assignments, priorities, deadlines and completion tracking.'],events:['★','Programs & Events','Plan programs and preserve complete event records.'],attendance:['◷','Attendance','Meeting and event attendance across every management term.'],assets:['▤','IT / Assets','Track computers, equipment, issues and repair history.'],documents:['▱','Documents','One searchable home for reports, proposals, notices and certificates.'],reports:['▥','Reports','Generate activity, attendance, event, task and IT reports.'],handover:['↗','Handover Center','Transfer the complete institutional record to the next Secretary.'],settings:['⚙','Settings','Club settings, roles, permissions and system configuration.']};
  const content=document.getElementById('content'),toast=document.getElementById('toast');let usbRoot=null,current='dashboard';
  function notify(t){if(!toast)return;toast.textContent=t;toast.classList.add('show');clearTimeout(window.__kitcToast);window.__kitcToast=setTimeout(()=>toast.classList.remove('show'),2200)}
  async function writeJson(file,value){if(!usbRoot)throw Error('KITC USB is not connected');const d=await usbRoot.getDirectoryHandle('database',{create:true}),h=await d.getFileHandle(file,{create:true}),w=await h.createWritable();try{await w.write(JSON.stringify(value,null,2))}finally{await w.close()}}
  async function readJson(file,fallback){if(!usbRoot)throw Error('KITC USB is not connected');try{const d=await usbRoot.getDirectoryHandle('database'),h=await d.getFileHandle(file),v=JSON.parse(await(await h.getFile()).text());if(!Array.isArray(v))throw Error(`${file} must contain a JSON array`);return v}catch(e){if(e.name==='NotFoundError')return JSON.parse(JSON.stringify(fallback));throw e}}
  async function saveAll(){if(!usbRoot){notify('Connect the KITC USB first');return false}try{for(const[k,f]of Object.entries(files))await writeJson(f,data[k]);notify('All KITC data saved to USB ✓');return true}catch(e){console.error(e);notify(`USB save failed: ${e.message||'Unknown error'}`);return false}}
  async function loadUsb(handle){if(!handle)return;usbRoot=handle;try{const loaded={};for(const[k,f]of Object.entries(files))loaded[k]=await readJson(f,seed[k]);Object.assign(data,loaded);window.kitcData=data;render(current);notify('KITC data loaded from USB ✓')}catch(e){console.error('KITC USB load failed',e);notify(`USB load failed: ${e.message||'Unknown error'}`)}}
  const head=(k,t,s,a='＋ Add',fn='openAdd()')=>`<div class="page-head"><div><div class="eyebrow">${k}</div><h1>${t}</h1><p>${s}</p></div><button class="button primary" onclick="${fn}">${a}</button></div>`;
  function dashboard(){return `${head('KITC • 2026–27','Good afternoon, Anim 👋','Secretary dashboard • records live on the connected KITC USB','＋ Quick Add','openAdd()')}<div class="stats"><div class="stat"><div class="stat-top">Members <span>↗</span></div><strong>${data.members.length}</strong><span class="trend">Active this term</span></div><div class="stat"><div class="stat-top">Pending Tasks <span>!</span></div><strong>${data.tasks.filter(x=>x[4]!=='Completed').length}</strong><span class="trend">Follow-up required</span></div><div class="stat"><div class="stat-top">Upcoming Events <span>★</span></div><strong>${data.events.filter(x=>x[3]!=='Completed').length}</strong><span class="trend">Next program</span></div><div class="stat"><div class="stat-top">Open Issues <span>⌁</span></div><strong>${data.issues.filter(x=>x[3]!=='Resolved').length}</strong><span class="trend">IT / assets</span></div></div><div class="grid-2"><div class="panel"><div class="panel-head"><h2>Today's priorities</h2><span class="muted">Aug 21, 2026</span></div><div class="list">${data.tasks.slice(0,4).map((t,i)=>`<div class="list-row"><div><strong>${t[0]}</strong><small>${t[1]} • due ${t[3]}</small></div><button class="pill action-pill" onclick="cycleTask(${i})">${t[4]}</button></div>`).join('')}</div></div><div class="panel"><div class="panel-head"><h2>Upcoming</h2><button class="text-button" onclick="render('events')">View all</button></div><div class="list">${data.events.slice(0,3).map(e=>`<div class="list-row"><div><strong>${e[0]}</strong><small>${e[1]} • ${e[2]}</small></div><span class="pill dark">${e[3]}</span></div>`).join('')}</div></div></div><div class="panel" style="margin-top:16px"><div class="panel-head"><h2>Quick actions</h2><span class="muted">Every change is persisted to USB</span></div><div class="quick-add"><button class="button" onclick="openAdd('meeting')">＋ Meeting</button><button class="button" onclick="openAdd('task')">＋ Task</button><button class="button" onclick="openAdd('event')">＋ Event</button><button class="button" onclick="openAdd('issue')">＋ IT Issue</button><button class="button" onclick="openAdd('member')">＋ Member</button></div></div>`}
  const defs={member:{title:'Member',key:'members',fields:['Name','Position','Class']},meeting:{title:'Meeting',key:'meetings',fields:['Meeting title','Date','Location']},task:{title:'Task',key:'tasks',fields:['Task','Assigned to','Deadline']},event:{title:'Event',key:'events',fields:['Event name','Date','Venue']},attendance:{title:'Attendance',key:'attendance',fields:['Record','Date','Present']},issue:{title:'IT Issue',key:'issues',fields:['Asset / PC','Issue','Priority']},document:{title:'Document',key:'documents',fields:['Document','Category','Date']}};
  function values(type,i){const d=defs[type],x=data[d.key][i];if(!x)return[];return type==='member'?[x.name,x.role,x.class]:x.slice(0,3)}
  function tablePage(key){if(key==='reports')return `${head('Analytics','Reports','Generate reports from USB records','Generate report','generateReport()')}<div class="section-grid">${['Monthly Activity Report','Member Attendance Report','Program History','Pending Task Report','IT Issue Report','Annual Secretary Report'].map(x=>`<article class="module-card" onclick="generateReport('${x}')"><div class="module-icon">▥</div><h3>${x}</h3><p>Generate from records stored on the KITC USB.</p></article>`).join('')}</div>`;if(key==='handover')return `${head('Continuity','Handover Center','Preserve the institutional record between Secretaries','Backup term','backupAll()')}<div class="handover-card"><h2>Secretary Handover</h2><p>Create a complete USB backup before transferring the system.</p></div>`;if(key==='settings')return `${head('System','Settings','KITC system configuration')}<div class="panel"><h2>USB storage</h2><p class="muted">The connected KITC USB is the source of truth for club records.</p></div>`;const m=modules[key],type=key==='assets'?'issue':key==='documents'?'document':key,d=defs[type];if(!d)return head(m[0],m[1],m[2]);const rows=data[d.key];return `${head(m[0],m[1],m[2],`＋ Add ${d.title.toLowerCase()}`,`openAdd('${type}')`)}<div class="table-card"><div class="table-toolbar"><strong>${m[1]}</strong><span class="muted">USB storage</span></div><table class="table"><thead><tr>${d.fields.map(c=>`<th>${c}</th>`).join('')}<th>Actions</th></tr></thead><tbody>${rows.map((x,i)=>{const v=type==='member'?[x.name,x.role,x.class]:x.slice(0,3);return `<tr>${v.map(z=>`<td>${String(z??'')}</td>`).join('')}<td><button class="text-button" onclick="editRecord('${type}',${i})">Edit</button></td></tr>`}).join('')}</tbody></table></div>`}
  function render(section='dashboard'){current=section;window.kitcCurrentSection=section;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.section===section));if(content)content.innerHTML=section==='dashboard'?dashboard():tablePage(section)}
  window.render=render;window.openAdd=(type='member',index=-1)=>{const d=defs[type];if(!d)return;const v=index>=0?values(type,index):[];document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="modal"><div class="modal"><button class="modal-close" onclick="closeModal()">×</button><div class="eyebrow">KITC • 2026–27 • USB</div><h2>${index>=0?'Edit ':'Add '}${d.title}</h2><form id="kitcRecordForm">${d.fields.map((f,i)=>`<label>${f}<input required name="f${i}" value="${String(v[i]??'').replace(/"/g,'&quot;')}" placeholder="${f}"></label>`).join('')}<button class="button primary" type="submit">Save to USB</button></form></div></div>`);document.getElementById('kitcRecordForm').onsubmit=e=>submitRecord(e,type,index)};
  window.closeModal=()=>document.getElementById('modal')?.remove();
  async function submitRecord(e,type,index){e.preventDefault();const d=defs[type],f=[...new FormData(e.target).values()];let value;if(type==='member')value={name:f[0],role:f[1],class:f[2],status:index>=0?data.members[index].status:'Active'};else if(type==='task')value=[f[0],f[1],index>=0?data.tasks[index][2]:'Medium',f[2],index>=0?data.tasks[index][4]:'Pending'];else if(type==='event')value=[f[0],f[1],f[2],index>=0?data.events[index][3]:'Planned'];else if(type==='meeting')value=[f[0],f[1],f[2],index>=0?data.meetings[index][3]:'Agenda pending'];else if(type==='issue')value=[f[0],f[1],f[2],index>=0?data.issues[index][3]:'Pending'];else value=f;if(index>=0)data[d.key][index]=value;else data[d.key].push(value);if(await saveAll()){window.closeModal();render(current)}}
  window.editRecord=(type,i)=>window.openAdd(type,i);window.cycleTask=async i=>{const s=['Pending','In Progress','Completed'],n=s.indexOf(data.tasks[i][4]);data.tasks[i][4]=s[(n+1)%3];if(await saveAll())render(current)};
  window.generateReport=async name=>{try{if(!usbRoot)throw Error('KITC USB is not connected');const d=await usbRoot.getDirectoryHandle('reports',{create:true}),h=await d.getFileHandle(String(name||'report').replace(/[^a-z0-9]+/gi,'-').toLowerCase()+'.json',{create:true}),w=await h.createWritable();await w.write(JSON.stringify({report:name,generatedAt:new Date().toISOString(),...data},null,2));await w.close();notify('Report saved to USB ✓')}catch(e){notify(`Report save failed: ${e.message}`)}};
  window.backupAll=async()=>{try{if(!usbRoot)throw Error('KITC USB is not connected');const d=await usbRoot.getDirectoryHandle('backups',{create:true}),h=await d.getFileHandle(`kitc-backup-${Date.now()}.json`,{create:true}),w=await h.createWritable();await w.write(JSON.stringify(data,null,2));await w.close();notify('Complete KITC backup saved ✓')}catch(e){notify(`Backup failed: ${e.message}`)}};
  document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>{render(b.dataset.section);document.getElementById('sidebar')?.classList.remove('open')}));
  document.getElementById('menuButton')?.addEventListener('click',()=>document.getElementById('sidebar')?.classList.toggle('open'));document.querySelector('.profile')?.addEventListener('click',()=>notify('Signed in as Anim • Secretary'));document.querySelector('.icon-button')?.addEventListener('click',()=>notify('KITC notifications are ready'));
  window.addEventListener('kitc:usb-ready',e=>loadUsb(e.detail?.handle));render('dashboard');
})();