(()=>{'use strict';
const KEYS=['members','meetings','tasks','events','attendance','issues','documents'];
const LABELS={members:'Members',meetings:'Meetings',tasks:'Tasks',events:'Programs & Events',attendance:'Attendance',issues:'IT / Assets',documents:'Documents'};
const MODULES={members:['♙','Members','Member records available in this workspace.'],meetings:['▣','Meetings','Agendas, attendees, minutes and follow-up records.'],tasks:['✓','My Tasks','Task assignments and status.'],events:['★','Events','Programs and event records.'],attendance:['◷','Attendance','Attendance records.'],assets:['▤','IT / Assets','Equipment and issue records.'],documents:['▱','Documents','Institutional documents.'],reports:['▥','Reports','Generate reusable reports from current records.'],handover:['↗','Handover Center','Preserve the institutional record for the next Secretary.'],settings:['⚙','Settings','Workspace settings and configuration.']};
const store=window.kitcData=window.kitcData||{};KEYS.forEach(k=>{if(!Array.isArray(store[k]))store[k]=[]});
let current='dashboard';
const content=document.getElementById('content'),toast=document.getElementById('toast');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const notify=t=>{if(!toast)return;toast.textContent=t;toast.classList.add('show');clearTimeout(window.__kitcToast);window.__kitcToast=setTimeout(()=>toast.classList.remove('show'),2400)};
const keyFor=s=>s==='assets'?'issues':s;
function normalize(k,r){if(Array.isArray(r)){const id=window.crypto?.randomUUID?window.crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`;if(k==='members')return{id,name:r[0]||'',role:r[1]||'',class:r[2]||'',status:r[3]||'Active'};return{id,values:r.slice()}}if(r&&typeof r==='object'){const id=r.id||(window.crypto?.randomUUID?window.crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`);if(k==='members')return{id,name:r.name||r.fullName||r.memberName||'',role:r.role||r.position||'',class:r.class||r.className||'',status:r.status||'Active'};if(Array.isArray(r.values))return{id,values:r.values};const known={meetings:['title','date','location','nextStep'],tasks:['task','assignedTo','priority','deadline','status'],events:['name','date','venue','status'],attendance:['record','date','present'],issues:['asset','issue','priority','status'],documents:['document','category','date']};return{id,values:(known[k]||[]).map(f=>r[f]??'')}}const id=window.crypto?.randomUUID?window.crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`;return{id,values:[]}}
function vals(k,r){return k==='members'?[r.name,r.role,r.class,r.status]:Array.isArray(r?.values)?r.values:[]}
function persist(){if(typeof window.kitcPersist==='function'&&!window.kitcPersist())notify('Could not save changes on this device');}
function head(k,t,s){return`<div class="page-head"><div><div class="eyebrow">${esc(k)}</div><h1>${esc(t)}</h1><p>${esc(s)}</p></div></div>`}
function title(k,r){return k==='members'?r.name:vals(k,r)[0]||'KITC Record'}
function dashboard(){return`${head('KITC • 2026–27','Good afternoon, Secretary 👋','Your workspace is ready. No USB or external device is required.')}<div class="stats"><div class="stat"><div class="stat-top">Members</div><strong>${store.members.length}</strong><span class="trend">Current records</span></div><div class="stat"><div class="stat-top">Pending Tasks</div><strong>${store.tasks.filter(r=>vals('tasks',r)[4]!=='Completed').length}</strong><span class="trend">Follow-up required</span></div><div class="stat"><div class="stat-top">Upcoming Events</div><strong>${store.events.filter(r=>vals('events',r)[3]!=='Completed').length}</strong><span class="trend">Next programs</span></div><div class="stat"><div class="stat-top">Open Issues</div><strong>${store.issues.filter(r=>vals('issues',r)[3]!=='Resolved').length}</strong><span class="trend">IT / assets</span></div></div>`}
function tablePage(section){const meta=MODULES[section]||MODULES.members;if(section==='reports')return`${head('Analytics','Reports','Generate reusable reports from current workspace records')}<div class="section-grid">${['Monthly Activity Report','Member Attendance Report','Program History','Pending Task Report','IT Issue Report','Annual Secretary Report'].map(x=>`<article class="module-card" onclick="generateReport('${esc(x)}')"><div class="module-icon">▥</div><h3>${esc(x)}</h3><p>Generate from current records.</p></article>`).join('')}</div>`;if(section==='handover')return`${head('Continuity','Handover Center','Preserve the institutional record for the next Secretary')}<div class="handover-card"><h2>Secretary Handover</h2><button class="button primary" onclick="backupAll()">Download complete backup</button></div>`;if(section==='settings')return`${head('System','Settings','Workspace settings and configuration')}<div class="panel"><h2>Browser storage</h2><p>Optional local storage is enabled for this device.</p><p class="muted">Opening the workspace never depends on a USB device. Account permissions are handled separately by the authenticated Admin Panel.</p></div>`;const key=keyFor(section),cols={members:['Name','Position','Class','Status'],meetings:['Meeting','Date','Location','Next step'],tasks:['Task','Assigned to','Priority','Deadline','Status'],events:['Event','Date','Venue','Status'],attendance:['Record','Date','Present'],issues:['Asset','Issue','Priority','Status'],documents:['Document','Category','Date']}[key]||['Record'];const rows=Array.isArray(store[key])?store[key]:[];const body=rows.map(r=>{const v=vals(key,r);return`<tr>${cols.map((_,i)=>`<td>${esc(v[i]??'')}</td>`).join('')}</tr>`}).join('')||`<tr><td colspan="${cols.length}"><div class="empty-state"><h3>No ${esc(meta[1])} records</h3><p>This section is empty right now. Records can be added through the appropriate workspace.</p></div></td></tr>`;return`${head(meta[0],meta[1],meta[2])}<div class="table-card"><div class="table-wrap"><table class="table"><thead><tr>${cols.map(c=>`<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${body}</tbody></table></div></div>`}
function render(s='dashboard'){try{current=s;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.section===s));if(content)content.innerHTML=s==='dashboard'?dashboard():tablePage(s);content?.setAttribute('data-kitc-rendered','true')}catch(e){console.error('KITC render error',s,e);if(content)content.innerHTML=`<div class="panel"><h2>Could not open ${esc(s)}</h2><p>${esc(e.message)}</p><button class="button primary" onclick="render('dashboard')">Back to Dashboard</button></div>`}}
window.render=render;window.renderDashboard=dashboard;
function normText(x){return String(x??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
function searchScore(q,text,fields){const n=normText(text),terms=normText(q).split(/\s+/).filter(Boolean);let score=0;terms.forEach(t=>{if(n===t)score+=100;if(n.startsWith(t))score+=70;if(n.includes(` ${t}`))score+=55;if(n.includes(t))score+=35;fields.forEach((f,i)=>{const nf=normText(f);if(nf===t)score+=120-i*5;else if(nf.startsWith(t))score+=90-i*3;else if(nf.includes(t))score+=55-i*2})});return score}
function universalSearch(q){const out=[];KEYS.forEach(k=>store[k].forEach(r=>{const f=vals(k,r),score=searchScore(q,[title(k,r),...f].join(' '),f);if(score>0)out.push({key:k,id:r.id,title:title(k,r),fields:f,score})}));return out.sort((a,b)=>b.score-a.score).slice(0,12)}
function hideSearchResults(){document.getElementById('searchResults')?.remove()}
function showSearchResults(q){hideSearchResults();if(!q.trim())return;const box=document.getElementById('globalSearch');if(!box)return;const rs=universalSearch(q);const html=rs.length?rs.map(r=>`<button class="search-result" onclick="render('${r.key==='issues'?'assets':r.key}');hideSearchResults()"><strong>${esc(r.title)}</strong><small>${esc(LABELS[r.key])} • ${esc(r.fields.filter(Boolean).slice(0,3).join(' • '))}</small></button>`).join(''):'<div class="search-empty">No related KITC records found</div>';box.insertAdjacentHTML('afterend',`<div id="searchResults" class="search-results">${html}</div>`)}
function bindSearch(){const input=document.getElementById('globalSearch');if(!input)return;input.addEventListener('input',()=>showSearchResults(input.value));input.addEventListener('keydown',e=>{if(e.key==='Escape'){input.value='';hideSearchResults()}if(e.key==='Enter'){const r=universalSearch(input.value)[0];if(r){render(r.key==='issues'?'assets':r.key);hideSearchResults()}}});document.addEventListener('click',e=>{if(!e.target.closest('.search')&&!e.target.closest('#searchResults'))hideSearchResults()})}
function downloadJSON(name,data){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
window.generateReport=name=>{downloadJSON(`${name.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.json`,{report:name,generatedAt:new Date().toISOString(),...store});notify('Report downloaded successfully ✓')};
window.backupAll=()=>{downloadJSON(`kitc-backup-${new Date().toISOString().slice(0,10)}.json`,store);notify('Complete KITC backup downloaded ✓')};
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>{render(b.dataset.section);document.getElementById('sidebar')?.classList.remove('open')}));document.getElementById('menuButton')?.addEventListener('click',()=>document.getElementById('sidebar')?.classList.toggle('open'));bindSearch();render();
})();
