(()=>{'use strict';
const KEYS=['members','meetings','tasks','events','attendance','issues','documents'];
const FILES=Object.fromEntries(KEYS.map(k=>[k,`${k}.json`]));
const LABELS={members:'Members',meetings:'Meetings',tasks:'Tasks',events:'Programs & Events',attendance:'Attendance',issues:'IT / Assets',documents:'Documents'};
const MODULES={members:['♙','Members','Profiles, management roles, contact details and member history.'],meetings:['▣','Meetings','Agendas, attendees, minutes, decisions and follow-up tasks.'],tasks:['✓','Tasks','Assignments, priorities, deadlines and completion tracking.'],events:['★','Programs & Events','Plan programs and preserve complete event records.'],attendance:['◷','Attendance','Meeting and event attendance across every management term.'],assets:['▤','IT / Assets','Track computers, equipment, issues and repair history.'],documents:['▱','Documents','One searchable home for reports, proposals, notices and certificates.'],reports:['▥','Reports','Generate activity, attendance, event, task and IT reports.'],handover:['↗','Handover Center','Transfer the complete institutional record to the next Secretary.'],settings:['⚙','Settings','Club settings, roles, permissions and system configuration.']};
const DEFS={member:{key:'members',title:'Member',fields:['Name','Position','Class']},meeting:{key:'meetings',title:'Meeting',fields:['Meeting title','Date','Location']},task:{key:'tasks',title:'Task',fields:['Task','Assigned to','Deadline']},event:{key:'events',title:'Event',fields:['Event name','Date','Venue']},attendance:{key:'attendance',title:'Attendance',fields:['Record','Date','Present']},issue:{key:'issues',title:'IT Issue',fields:['Asset / PC','Issue','Priority']},document:{key:'documents',title:'Document',fields:['Document','Category','Date']}};
const store=window.kitcData=window.kitcData||{};KEYS.forEach(k=>{if(!Array.isArray(store[k]))store[k]=[]});
let usbRoot=window.kitcUsbHandle||null;let current='dashboard';
const content=document.getElementById('content');const toast=document.getElementById('toast');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>window.crypto?.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`;
const notify=t=>{if(!toast)return;toast.textContent=t;toast.classList.add('show');clearTimeout(window.__kitcToast);window.__kitcToast=setTimeout(()=>toast.classList.remove('show'),2400)};
const keyFor=s=>s==='assets'?'issues':s;const typeFor=s=>s==='assets'?'issue':s==='documents'?'document':s;
function normalize(k,r){if(Array.isArray(r)){const id=uid();if(k==='members')return{id,name:r[0]||'',role:r[1]||'',class:r[2]||'',status:r[3]||'Active'};return{id,values:r.slice()}}if(r&&typeof r==='object'){const id=r.id||uid();if(k==='members')return{id,name:r.name||r.fullName||r.memberName||'',role:r.role||r.position||'',class:r.class||r.className||'',status:r.status||'Active'};if(Array.isArray(r.values))return{id,values:r.values};const known={meetings:['title','date','location','nextStep'],tasks:['task','assignedTo','priority','deadline','status'],events:['name','date','venue','status'],attendance:['record','date','present'],issues:['asset','issue','priority','status'],documents:['document','category','date']};return{id,values:(known[k]||[]).map(f=>r[f]??'')}}return{id:uid(),values:[]}}
function vals(k,r){return k==='members'?[r.name,r.role,r.class,r.status]:Array.isArray(r?.values)?r.values:[]}
async function db(){if(!usbRoot)throw Error('KITC USB is not connected');return usbRoot.getDirectoryHandle('database',{create:true})}
async function read(k){const d=await db();try{const f=await d.getFileHandle(FILES[k]);const p=JSON.parse(await(await f.getFile()).text());const a=Array.isArray(p)?p:Array.isArray(p?.[k])?p[k]:Array.isArray(p?.records)?p.records:null;if(!a)throw Error(`${FILES[k]} is not a valid KITC record file`);return a.map(r=>normalize(k,r))}catch(e){if(e.name==='NotFoundError')return[];throw e}}
async function write(k){const d=await db();const f=await d.getFileHandle(FILES[k],{create:true});const w=await f.createWritable();try{await w.write(JSON.stringify(store[k],null,2))}finally{await w.close()}}
async function save(keys=KEYS){if(!usbRoot){notify('Connect the KITC USB first');return false}try{for(const k of keys)await write(k);return true}catch(e){notify(`USB save failed: ${e.message}`);return false}}
window.kitcSaveAll=()=>save(KEYS);window.kitcSave=key=>save([key]);
async function loadUsb(root){usbRoot=root;window.kitcUsbHandle=root;try{for(const k of KEYS)store[k]=await read(k);window.kitcData=store;window.kitcDataReady=true;render(current);notify(`USB records loaded • ${store.members.length} members`)}catch(e){window.kitcDataReady=false;console.error(e);notify(`USB load failed: ${e.message}`)}}
window.addEventListener('kitc:usb-ready',e=>{if(e.detail?.handle)loadUsb(e.detail.handle)});
function head(k,t,s,a='＋ Add',fn='openAdd()'){return`<div class="page-head"><div><div class="eyebrow">${esc(k)}</div><h1>${esc(t)}</h1><p>${esc(s)}</p></div><button class="button primary" onclick="${fn}">${esc(a)}</button></div>`}
function title(k,r){return k==='members'?r.name:vals(k,r)[0]||'KITC Record'}
function dashboard(){return`${head('KITC • 2026–27','Good afternoon, Anim 👋','Secretary dashboard • USB is the source of truth','＋ Quick Add','openAdd()')}<div class="stats"><div class="stat"><div class="stat-top">Members</div><strong>${store.members.length}</strong><span class="trend">Current records</span></div><div class="stat"><div class="stat-top">Pending Tasks</div><strong>${store.tasks.filter(r=>vals('tasks',r)[4]!=='Completed').length}</strong><span class="trend">Follow-up required</span></div><div class="stat"><div class="stat-top">Upcoming Events</div><strong>${store.events.filter(r=>vals('events',r)[3]!=='Completed').length}</strong><span class="trend">Next programs</span></div><div class="stat"><div class="stat-top">Open Issues</div><strong>${store.issues.filter(r=>vals('issues',r)[3]!=='Resolved').length}</strong><span class="trend">IT / assets</span></div></div>`}
function tablePage(section){const meta=MODULES[section]||MODULES.members;if(section==='reports')return`${head('Analytics','Reports','Generate reusable reports from USB records','Generate report','generateReport()')}<div class="section-grid">${['Monthly Activity Report','Member Attendance Report','Program History','Pending Task Report','IT Issue Report','Annual Secretary Report'].map(x=>`<article class="module-card" onclick="generateReport('${esc(x)}')"><div class="module-icon">▥</div><h3>${esc(x)}</h3><p>Generate from USB records.</p></article>`).join('')}</div>`;if(section==='handover')return`${head('Continuity','Handover Center','Preserve the complete institutional record','Backup term','backupAll()')}<div class="handover-card"><h2>Secretary Handover</h2><button class="button primary" onclick="backupAll()">Create complete USB backup</button></div>`;if(section==='settings')return`${head('System','Settings','Club settings and configuration')}<div class="panel"><h2>USB storage</h2><p>${usbRoot?'KITC USB connected ✓':'KITC USB not connected.'}</p></div>`;const key=keyFor(section);const type=typeFor(section);const def=DEFS[type];const cols={members:['Name','Position','Class','Status'],meetings:['Meeting','Date','Location','Next step'],tasks:['Task','Assigned to','Priority','Deadline','Status'],events:['Event','Date','Venue','Status'],attendance:['Record','Date','Present'],issues:['Asset','Issue','Priority','Status'],documents:['Document','Category','Date']}[key]||['Record'];const rows=Array.isArray(store[key])?store[key]:[];let body=rows.map(r=>{const v=vals(key,r);return`<tr><td><input class="record-check" type="checkbox" data-id="${esc(r.id)}"></td>${cols.map((_,i)=>`<td>${esc(v[i]??'')}</td>`).join('')}<td><button class="text-button" onclick="openAdd('${type}','${esc(r.id)}')">Edit</button><button class="icon-button record-more" type="button" data-id="${esc(r.id)}">⋮</button></td></tr>`}).join('');if(!body)body=`<tr><td colspan="${cols.length+2}"><div class="empty-state"><h3>No ${esc(meta[1])} records</h3><p>There are no records loaded from the KITC USB yet.</p><button class="button primary" onclick="openAdd('${type}')">＋ Add ${esc(def?.title||meta[1])}</button></div></td></tr>`;return`${head(meta[0],meta[1],meta[2],`＋ Add ${def?.title?.toLowerCase()||'record'}`,`openAdd('${type}')`)}<div class="table-card"><div class="record-toolbar"><label><input type="checkbox" id="selectAllRecords"> Select all</label><span id="selectedCount">0 selected</span><button class="button danger" id="deleteSelected" style="display:none">Delete selected</button></div><div class="table-wrap"><table class="table"><thead><tr><th></th>${cols.map(c=>`<th>${esc(c)}</th>`).join('')}<th>Actions</th></tr></thead><tbody>${body}</tbody></table></div></div>`}
function render(s='dashboard'){try{current=s;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.section===s));if(content)content.innerHTML=s==='dashboard'?dashboard():tablePage(s);bindTableActions()}catch(e){console.error('KITC render error',s,e);if(content)content.innerHTML=`<div class="panel"><h2>Could not open ${esc(s)}</h2><p>${esc(e.message)}</p><button class="button primary" onclick="render('dashboard')">Back to Dashboard</button></div>`}}
window.render=render;window.renderDashboard=dashboard;
function record(type,id){const k=DEFS[type]?.key;return k?store[k].find(r=>r.id===id):null}
function formVals(type,r){return type==='member'?[r?.name,r?.role,r?.class]:(r?.values||[]).slice(0,3)}
window.openAdd=(type='member',id=null)=>{const d=DEFS[type];if(!d)return notify('This section is not editable yet');const old=id?record(type,id):null;const v=formVals(type,old);document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="modal"><div class="modal"><button class="modal-close" onclick="closeModal()">×</button><div class="eyebrow">KITC • USB</div><h2>${old?'Edit ':'Add '}${esc(d.title)}</h2><form id="kitcRecordForm">${d.fields.map((f,i)=>`<label>${esc(f)}<input required name="f${i}" value="${esc(v[i]||'')}"></label>`).join('')}<button class="button primary">Save to USB</button></form></div></div>`);document.getElementById('kitcRecordForm').onsubmit=e=>submitRecord(e,type,id)};
window.closeModal=()=>document.getElementById('modal')?.remove();
async function submitRecord(e,type,id){e.preventDefault();const d=DEFS[type];const k=d.key;const f=[...new FormData(e.target).values()];const old=id?record(type,id):null;let r;if(type==='member'){r={id:old?.id||uid(),name:f[0],role:f[1],class:f[2],status:old?.status||'Active'}}else{const ov=old?.values||[];r={id:old?.id||uid(),values:f};if(type==='task')r.values=[f[0],f[1],ov[2]||'Medium',f[2],ov[4]||'Pending'];if(type==='event')r.values=[f[0],f[1],f[2],ov[3]||'Planned'];if(type==='meeting')r.values=[f[0],f[1],f[2],ov[3]||'Agenda pending'];if(type==='issue')r.values=[f[0],f[1],f[2],ov[3]||'Pending']}const i=old?store[k].findIndex(x=>x.id===id):-1;if(i>=0)store[k][i]=r;else store[k].push(r);if(await save([k])){closeModal();render(current);notify(`${d.title} saved to USB ✓`)}}
async function deleteRecords(type,ids){const k=DEFS[type]?.key;if(!k)return;const set=new Set(ids);store[k]=store[k].filter(r=>!set.has(r.id));if(await save([k])){render(current);notify(`${ids.length} record${ids.length>1?'s':''} deleted from USB ✓`)}}
function bindTableActions(){const type=typeFor(current);if(!DEFS[type])return;const all=document.getElementById('selectAllRecords');const checks=[...document.querySelectorAll('.record-check')];const btn=document.getElementById('deleteSelected');const count=document.getElementById('selectedCount');const sync=()=>{const n=checks.filter(c=>c.checked).length;if(count)count.textContent=`${n} selected`;if(btn)btn.style.display=n?'inline-flex':'none';if(all)all.checked=checks.length>0&&n===checks.length};checks.forEach(c=>c.addEventListener('change',sync));if(all)all.addEventListener('change',()=>{checks.forEach(c=>{c.checked=all.checked});sync()});if(btn)btn.addEventListener('click',()=>{const ids=checks.filter(c=>c.checked).map(c=>c.dataset.id);if(ids.length&&confirm(`Delete ${ids.length} selected record${ids.length>1?'s':''}?`))deleteRecords(type,ids)});document.querySelectorAll('.record-more').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.id;document.getElementById('recordMenu')?.remove();b.insertAdjacentHTML('afterend',`<div id="recordMenu" class="record-menu"><button onclick="openAdd('${type}','${esc(id)}');this.parentElement.remove()">✏️ Edit</button><button onclick="if(confirm('Delete this record?'))deleteRecords('${type}',['${esc(id)}']);this.parentElement.remove()">🗑️ Delete</button></div>`)}))}
function normText(x){return String(x??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
function searchScore(q,text,fields){const n=normText(text);const terms=normText(q).split(/\s+/).filter(Boolean);let score=0;terms.forEach(t=>{if(n===t)score+=100;if(n.startsWith(t))score+=70;if(n.includes(` ${t}`))score+=55;if(n.includes(t))score+=35;fields.forEach((f,i)=>{const nf=normText(f);if(nf===t)score+=120-i*5;else if(nf.startsWith(t))score+=90-i*3;else if(nf.includes(t))score+=55-i*2})});return score}
function universalSearch(q){const out=[];KEYS.forEach(k=>store[k].forEach(r=>{const f=vals(k,r);const score=searchScore(q,[title(k,r),...f].join(' '),f);if(score>0)out.push({key:k,id:r.id,title:title(k,r),fields:f,score})}));return out.sort((a,b)=>b.score-a.score).slice(0,12)}
function hideSearchResults(){document.getElementById('searchResults')?.remove()}
function showSearchResults(q){hideSearchResults();if(!q.trim())return;const box=document.getElementById('globalSearch');if(!box)return;const rs=universalSearch(q);const html=rs.length?rs.map(r=>`<button class="search-result" onclick="render('${r.key==='issues'?'assets':r.key}');hideSearchResults()"><strong>${esc(r.title)}</strong><small>${esc(LABELS[r.key])} • ${esc(r.fields.filter(Boolean).slice(0,3).join(' • '))}</small></button>`).join(''):'<div class="search-empty">No related KITC records found</div>';box.insertAdjacentHTML('afterend',`<div id="searchResults" class="search-results">${html}</div>`)}
function bindSearch(){const input=document.getElementById('globalSearch');if(!input)return;input.addEventListener('input',()=>showSearchResults(input.value));input.addEventListener('keydown',e=>{if(e.key==='Escape'){input.value='';hideSearchResults()}if(e.key==='Enter'){const r=universalSearch(input.value)[0];if(r){render(r.key==='issues'?'assets':r.key);hideSearchResults()}}});document.addEventListener('click',e=>{if(!e.target.closest('.search')&&!e.target.closest('#searchResults'))hideSearchResults()})}
window.cycleTask=async id=>{const r=store.tasks.find(x=>x.id===id);if(!r)return;const v=r.values;const states=['Pending','In Progress','Completed'];const index=states.indexOf(v[4]);v[4]=states[(index+1)%states.length];if(await save(['tasks']))render(current)};
window.generateReport=async name=>{if(!usbRoot)return notify('Connect the KITC USB first');try{const d=await usbRoot.getDirectoryHandle('reports',{create:true});const f=await d.getFileHandle(`${name.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.json`,{create:true});const w=await f.createWritable();await w.write(JSON.stringify({report:name,generatedAt:new Date().toISOString(),...store},null,2));await w.close();notify('Report saved to USB ✓')}catch(e){notify(`Report failed: ${e.message}`)}};
window.backupAll=async()=>{if(!usbRoot)return notify('Connect the KITC USB first');try{const d=await usbRoot.getDirectoryHandle('backups',{create:true});const f=await d.getFileHandle(`kitc-backup-${Date.now()}.json`,{create:true});const w=await f.createWritable();await w.write(JSON.stringify(store,null,2));await w.close();notify('Complete KITC backup saved ✓')}catch(e){notify(`Backup failed: ${e.message}`)}};
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>{render(b.dataset.section);document.getElementById('sidebar')?.classList.remove('open')}));document.getElementById('menuButton')?.addEventListener('click',()=>document.getElementById('sidebar')?.classList.toggle('open'));bindSearch();render();
})();
