import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Search, Bell, Plus, Home, Users, CalendarDays, CheckSquare, PartyPopper, Monitor, FolderOpen, BarChart3, ArrowRightLeft, Settings, Megaphone, ClipboardList, ChevronRight, CircleCheck, Clock3, AlertTriangle, Menu, X, Download, UserRound, FileText, Laptop, Sparkles } from 'lucide-react';
import './styles.css';

const nav = [
  ['dashboard','Dashboard',Home], ['members','Members',Users], ['meetings','Meetings',CalendarDays], ['tasks','Tasks',CheckSquare], ['events','Events',PartyPopper], ['attendance','Attendance',ClipboardList], ['assets','IT / Assets',Monitor], ['documents','Documents',FolderOpen], ['announcements','Announcements',Megaphone], ['reports','Reports',BarChart3], ['handover','Handover Center',ArrowRightLeft], ['settings','Settings',Settings]
];

const seed = {
  members:[
    {id:1,name:'Anim Katwal',role:'Secretary',class:'12',section:'A',status:'Active',attendance:92,phone:'+977 98XXXXXXXX',email:'secretary@kcitc.local'},
    {id:2,name:'Prashna Shrestha',role:'President',class:'12',section:'A',status:'Active',attendance:96,phone:'+977 98XXXXXXXX',email:'president@kcitc.local'},
    {id:3,name:'Prakash Rai',role:'Vice-President',class:'11',section:'B',status:'Active',attendance:88,phone:'+977 98XXXXXXXX',email:'vp@kcitc.local'},
    {id:4,name:'Mamata Dhamala',role:'Member',class:'11',section:'A',status:'Active',attendance:94,phone:'+977 98XXXXXXXX',email:'member@kcitc.local'},
  ],
  tasks:[
    {id:1,title:'Prepare management meeting agenda',assignee:'Anim Katwal',priority:'High',deadline:'Aug 25, 2026',status:'Pending'},
    {id:2,title:'Complete computer lab inspection report',assignee:'Anim Katwal',priority:'Medium',deadline:'Aug 24, 2026',status:'In Progress'},
    {id:3,title:'Confirm IT workshop venue',assignee:'Prakash Rai',priority:'Medium',deadline:'Aug 26, 2026',status:'Pending'},
    {id:4,title:'Upload last event report',assignee:'Mamata Dhamala',priority:'Low',deadline:'Aug 20, 2026',status:'Completed'}
  ],
  meetings:[
    {id:1,title:'Management Meeting #04',date:'Aug 25, 2026',location:'Computer Lab',attendees:9,agenda:'IT workshop, membership drive, pending tasks'},
    {id:2,title:'Management Meeting #03',date:'Aug 12, 2026',location:'Room 204',attendees:11,agenda:'Annual program planning'}
  ],
  events:[
    {id:1,title:'KCITC IT Workshop 2026',date:'Aug 28, 2026',venue:'Computer Lab',status:'Planning',participants:'52',description:'Hands-on workshop focused on practical IT skills.'},
    {id:2,title:'Computer Lab Inspection',date:'Aug 21, 2026',venue:'Computer Lab',status:'In Progress',participants:'4',description:'Inspection of 50 lab computers and peripherals.'}
  ],
  issues:[{id:'PC-27',title:'Keyboard not working',asset:'PC-27',priority:'Medium',status:'Pending',assigned:'IT Team'}],
  announcements:[{id:1,title:'Management meeting scheduled',content:'The next management meeting is scheduled for August 25.',date:'Aug 21, 2026'}]
};

function App(){
 const [page,setPage]=useState('dashboard'); const [mobile,setMobile]=useState(false); const [search,setSearch]=useState(''); const [tasks,setTasks]=useState(seed.tasks); const [toast,setToast]=useState('');
 const [members]=useState(seed.members);
 const counts=useMemo(()=>({members:members.length,tasks:tasks.filter(t=>t.status!=='Completed').length,events:seed.events.filter(e=>e.status!=='Completed').length,issues:seed.issues.filter(i=>i.status!=='Resolved').length}),[members,tasks]);
 const notify=(msg)=>{setToast(msg);setTimeout(()=>setToast(''),2200)};
 const filteredMembers=members.filter(m=>`${m.name} ${m.role} ${m.class}`.toLowerCase().includes(search.toLowerCase()));
 const filteredTasks=tasks.filter(t=>`${t.title} ${t.assignee} ${t.priority} ${t.status}`.toLowerCase().includes(search.toLowerCase()));
 const toggleTask=id=>setTasks(ts=>ts.map(t=>t.id===id?{...t,status:t.status==='Completed'?'Pending':'Completed'}:t));
 return <div className="app">
  <aside className={`sidebar ${mobile?'open':''}`}><div className="brand"><div className="brandMark">K</div><div><b>KCITC</b><span>Secretary Hub</span></div><button className="iconBtn mobileClose" onClick={()=>setMobile(false)}><X size={20}/></button></div>
   <div className="term"><span>Current term</span><b>2026–27</b><small>Secretary • Anim Katwal</small></div>
   <nav>{nav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setMobile(false)}}><Icon size={18}/><span>{label}</span>{['tasks','events'].includes(id)&&<em>{id==='tasks'?counts.tasks:counts.events}</em>}</button>)}</nav>
   <div className="sidebarBottom"><div className="secure"><span className="dot"/>System online</div><small>KCITC Digital Management System</small></div>
  </aside>
  <main><header><button className="iconBtn menuBtn" onClick={()=>setMobile(true)}><Menu size={22}/></button><div className="search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search members, PC-27, events, documents..."/><kbd>⌘ K</kbd></div><button className="iconBtn" onClick={()=>notify('No new notifications')}><Bell size={19}/></button><div className="profile"><div className="avatar">AK</div><div><b>Anim Katwal</b><span>Secretary</span></div></div></header>
   <div className="content">{page==='dashboard'?<Dashboard counts={counts} tasks={tasks} onTask={toggleTask} go={setPage}/>:page==='members'?<Members members={filteredMembers}/>:page==='tasks'?<Tasks tasks={filteredTasks} onTask={toggleTask}/>:page==='meetings'?<Meetings/>:page==='events'?<Events/>:page==='attendance'?<Attendance members={members}/>:page==='assets'?<Assets/>:page==='documents'?<Documents/>:page==='announcements'?<Announcements/>:page==='reports'?<Reports notify={notify}/>:page==='handover'?<Handover notify={notify}/>:<Settings/>}</div>
  </main>{toast&&<div className="toast"><CircleCheck size={18}/>{toast}</div>}
 </div>
}
function Header({eyebrow,title,sub,action}){return <div className="pageHeader"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{sub}</p></div>{action}</div>}
function Dashboard({counts,tasks,onTask,go}){return <><Header eyebrow="KCITC DIGITAL MANAGEMENT SYSTEM" title="Good afternoon, Anim 👋" sub="Your Secretary workspace for the 2026–27 management term." action={<button className="primary" onClick={()=>go('tasks')}><Plus size={17}/> Add task</button>}/><div className="stats"><Stat icon={Users} label="Members" value={counts.members}/><Stat icon={CheckSquare} label="Pending tasks" value={counts.tasks}/><Stat icon={PartyPopper} label="Upcoming events" value={counts.events}/><Stat icon={AlertTriangle} label="Open issues" value={counts.issues}/></div><div className="grid2"><section className="card"><div className="cardHead"><div><h2>Today's priorities</h2><p>Things that need your attention.</p></div><button className="link" onClick={()=>go('tasks')}>View all <ChevronRight size={16}/></button></div>{tasks.filter(t=>t.status!=='Completed').slice(0,3).map(t=><TaskRow key={t.id} task={t} onTask={onTask}/>)}</section><section className="card"><div className="cardHead"><div><h2>Upcoming</h2><p>Meetings and programs.</p></div><button className="iconBtn" onClick={()=>go('events')}><CalendarDays size={18}/></button></div><EventMini title="Management Meeting #04" date="Aug 25" meta="Computer Lab"/><EventMini title="KCITC IT Workshop 2026" date="Aug 28" meta="Computer Lab"/></section></div><div className="grid2"><section className="card"><div className="cardHead"><div><h2>Recent activity</h2><p>Latest changes across the system.</p></div></div><Activity text="Anim created Computer Lab Inspection" time="12 min ago"/><Activity text="Mamata uploaded an event report" time="1 hr ago"/><Activity text="Prakash updated a task" time="2 hrs ago"/></section><section className="card spotlight"><Sparkles size={22}/><div><h2>Built for the next Secretary</h2><p>Every meeting, task, event and document stays connected so the club doesn't lose institutional memory when the term changes.</p><button className="link" onClick={()=>go('handover')}>Open Handover Center <ChevronRight size={16}/></button></div></section></div></>}
function Stat({icon:Icon,label,value}){return <div className="stat"><div className="statIcon"><Icon size={19}/></div><div><span>{label}</span><strong>{value}</strong></div></div>}
function TaskRow({task,onTask}){return <div className="taskRow"><button className={`check ${task.status==='Completed'?'done':''}`} onClick={()=>onTask(task.id)}>{task.status==='Completed'&&<CircleCheck size={16}/>}</button><div className="taskMain"><b>{task.title}</b><span>{task.assignee} • {task.deadline}</span></div><Badge text={task.priority}/><Badge text={task.status}/></div>}
function Badge({text}){return <span className={`badge ${text.toLowerCase().replaceAll(' ','-')}`}>{text}</span>}
function EventMini({title,date,meta}){return <div className="eventMini"><div className="dateBox"><b>{date.split(' ')[1]}</b><span>{date.split(' ')[0]}</span></div><div><b>{title}</b><span>{meta}</span></div><ChevronRight size={17}/></div>}
function Activity({text,time}){return <div className="activity"><div className="activityDot"/><div><b>{text}</b><span>{time}</span></div></div>}
function Members({members}){return <><Header eyebrow="PEOPLE" title="Members" sub="Manage members, positions and club participation." action={<button className="primary"><Plus size={17}/> Add member</button>}/><div className="toolbar"><span>{members.length} members</span><div className="filters"><button>All</button><button>Management</button><button>Active</button></div></div><section className="card tableCard"><table><thead><tr><th>Member</th><th>Position</th><th>Class</th><th>Attendance</th><th>Status</th><th></th></tr></thead><tbody>{members.map(m=><tr key={m.id}><td><div className="person"><div className="avatar small">{m.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><b>{m.name}</b><span>{m.email}</span></div></div></td><td>{m.role}</td><td>{m.class} • {m.section}</td><td><b>{m.attendance}%</b></td><td><Badge text={m.status}/></td><td><button className="iconBtn"><ChevronRight size={17}/></button></td></tr>)}</tbody></table></section></>}
function Tasks({tasks,onTask}){return <><Header eyebrow="WORK MANAGEMENT" title="Tasks" sub="Track responsibilities from decision to completion." action={<button className="primary"><Plus size={17}/> New task</button>}/><div className="stats compact"><Stat icon={Clock3} label="Pending" value={tasks.filter(t=>t.status==='Pending').length}/><Stat icon={AlertTriangle} label="In progress" value={tasks.filter(t=>t.status==='In Progress').length}/><Stat icon={CircleCheck} label="Completed" value={tasks.filter(t=>t.status==='Completed').length}/></div><section className="card taskList">{tasks.map(t=><TaskRow key={t.id} task={t} onTask={onTask}/>)}</section></>}
function Meetings(){return <><Header eyebrow="GOVERNANCE" title="Meetings" sub="Searchable history of agendas, attendees, decisions and minutes." action={<button className="primary"><Plus size={17}/> New meeting</button>}/><section className="card timeline">{seed.meetings.map(m=><div className="timelineItem" key={m.id}><div className="timelineIcon"><CalendarDays size={18}/></div><div className="timelineBody"><div className="rowBetween"><div><h3>{m.title}</h3><span>{m.date} • {m.location}</span></div><Badge text="Recorded"/></div><p>{m.agenda}</p><div className="meta"><Users size={14}/> {m.attendees} attendees <span>•</span> Minutes available <ChevronRight size={15}/></div></div></div>)}</section></>}
function Events(){return <><Header eyebrow="PROGRAMS" title="Events & Programs" sub="A permanent record from planning through final report." action={<button className="primary"><Plus size={17}/> Create event</button>}/><div className="eventGrid">{seed.events.map(e=><div className="card eventCard" key={e.id}><div className="eventCover"><PartyPopper size={25}/><Badge text={e.status}/></div><div className="eventBody"><span>{e.date} • {e.venue}</span><h2>{e.title}</h2><p>{e.description}</p><div className="eventMeta"><span><Users size={15}/> {e.participants} participants</span><span><ClipboardList size={15}/> Tasks</span><span><FolderOpen size={15}/> Documents</span></div><button className="link">Open event <ChevronRight size={16}/></button></div></div>)}</div></>}
function Attendance({members}){return <><Header eyebrow="PARTICIPATION" title="Attendance" sub="A unified view of member participation across meetings and events."/><section className="card tableCard"><table><thead><tr><th>Member</th><th>Overall</th><th>Meetings</th><th>Events</th><th>Status</th></tr></thead><tbody>{members.map(m=><tr key={m.id}><td><div className="person"><div className="avatar small">{m.name[0]}</div><b>{m.name}</b></div></td><td><div className="progress"><i style={{width:`${m.attendance}%`}}/></div><b>{m.attendance}%</b></td><td>8 / 9</td><td>5 / 5</td><td><Badge text="Active"/></td></tr>)}</tbody></table></section></>}
function Assets(){return <><Header eyebrow="IT OPERATIONS" title="IT / Assets" sub="Track equipment and every issue across its lifetime." action={<button className="primary"><Plus size={17}/> Add asset</button>}/><div className="assetStats"><div className="card assetHero"><Laptop size={26}/><div><span>Computer Lab</span><strong>50 devices</strong><small>Last inspection: Aug 21, 2026</small></div></div><div className="card assetHero"><AlertTriangle size={26}/><div><span>Open issues</span><strong>{seed.issues.length}</strong><small>1 medium priority issue</small></div></div></div><section className="card tableCard"><table><thead><tr><th>Asset</th><th>Type</th><th>Location</th><th>Condition</th><th>Issue history</th></tr></thead><tbody>{['PC-27','PC-01','PC-02','Projector-01'].map((x,i)=><tr key={x}><td><b>{x}</b></td><td>{i<3?'Desktop':'Projector'}</td><td>Computer Lab</td><td><Badge text={x==='PC-27'?'Needs attention':'Good'}/></td><td>{x==='PC-27'?1:0} issues <ChevronRight size={15}/></td></tr>)}</tbody></table></section></>}
function Documents(){return <><Header eyebrow="RECORDS" title="Documents" sub="One searchable home for reports, proposals, certificates and notices." action={<button className="primary"><Plus size={17}/> Upload</button>}/><div className="docGrid">{['Meeting Records','Event Reports','Certificates','Notices','Installation Records','Other'].map((x,i)=><div className="card docCard" key={x}><div className="docIcon"><FileText size={20}/></div><div><h3>{x}</h3><span>{[12,8,15,5,4,9][i]} files</span></div><ChevronRight size={17}/></div>)}</div></>}
function Announcements(){return <><Header eyebrow="COMMUNICATION" title="Announcements" sub="Official notices for the club." action={<button className="primary"><Plus size={17}/> New notice</button>}/><section className="card announcementList">{seed.announcements.map(a=><div className="announcement" key={a.id}><div className="announcementIcon"><Megaphone size={18}/></div><div><h3>{a.title}</h3><p>{a.content}</p><span>{a.date} • Posted by Anim Katwal</span></div></div>)}</section></>}
function Reports({notify}){const reports=['Monthly activity report','Member attendance report','Program history','Pending-task report','IT issue report','Annual Secretary report'];return <><Header eyebrow="ANALYTICS" title="Reports" sub="Generate operational summaries and export them for handover."/><div className="reportGrid">{reports.map((r,i)=><div className="card reportCard" key={r}><div className="reportIcon"><BarChart3 size={20}/></div><div><h3>{r}</h3><p>Live from current KCITC records.</p></div><button className="iconBtn" onClick={()=>notify(`Preparing ${r}`)}><Download size={17}/></button></div>)}</div></>}
function Handover({notify}){return <><Header eyebrow="CONTINUITY" title="Secretary Handover Center" sub="Transfer responsibility without losing the club's history."/><section className="card handoverHero"><div className="handoverIcon"><ArrowRightLeft size={26}/></div><div><span>Current term</span><h2>2026–27 → 2027–28</h2><p>Records remain archived. The next Secretary receives the active workspace, pending work and operational knowledge.</p></div><button className="primary" onClick={()=>notify('Handover checklist opened')}>Start handover</button></section><div className="handoverGrid">{['Members','Management history','Meetings','Events','Attendance','Documents','Tasks & issues','Important contacts','Secretary notes'].map(x=><div className="card handoverItem" key={x}><CircleCheck size={18}/><span>{x}</span></div>)}</div></>}
function Settings(){return <><Header eyebrow="SYSTEM" title="Settings" sub="Club identity, roles, permissions and system information."/><div className="settingsGrid"><div className="card settingCard"><h3>Club configuration</h3><label>Club name<input value="KCITC" readOnly/></label><label>Current term<input value="2026–27" readOnly/></label><label>Current Secretary<input value="Anim Katwal" readOnly/></label></div><div className="card settingCard"><h3>Roles & permissions</h3>{['Secretary — Full access','President — Overview + approvals','Vice-President — Tasks + events','Member — Limited access','Advisor — Reports + oversight'].map(x=><div className="role" key={x}><UserRound size={16}/><span>{x}</span><ChevronRight size={15}/></div>)}</div></div></>}

createRoot(document.getElementById('root')).render(<App/>);
