(()=>{'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const list=v=>Array.isArray(v)?v.flatMap(x=>String(x??'').split(/[,;|]/)).map(x=>x.trim()).filter(Boolean):String(v??'').split(/[,;|]/).map(x=>x.trim()).filter(Boolean);
const data=()=>window.kitcData||{};
function openProfile(id){const r=(data().members||[]).find(x=>String(x.id)===String(id));if(!r)return;document.getElementById('kitcMemberProfile')?.remove();const skills=list(r.skills?.length?r.skills:r.skill),interests=list(r.interests?.length?r.interests:r.interest);const tag=(items,icon)=>items.length?items.map(x=>`<span class="kitc-profile-tag">${icon} ${esc(x)}</span>`).join(''):'<span class="kitc-profile-empty">None recorded</span>';document.body.insertAdjacentHTML('beforeend',`<div class="kitc-profile-overlay" id="kitcMemberProfile"><aside class="kitc-profile-panel" role="dialog" aria-modal="true" aria-label="Member profile"><button class="kitc-profile-close" type="button" aria-label="Close">×</button><div class="kitc-profile-avatar">${esc(String(r.name||'?').trim().charAt(0).toUpperCase())}</div><div class="kitc-profile-eyebrow">KITC MEMBER</div><h2>${esc(r.name)}</h2><p class="kitc-profile-id">${esc(r.id||'No member ID')}</p><span class="kitc-profile-status">${esc(r.status||'Active')}</span><div class="kitc-profile-section"><h3>🎓 Academic</h3><div class="kitc-profile-grid"><div><small>Class / Program</small><strong>${esc(r.class||r.program||'—')}</strong></div><div><small>Section</small><strong>${esc(r.section||'—')}</strong></div><div><small>Semester</small><strong>${esc(r.semester||'—')}</strong></div><div><small>Track</small><strong>${esc(r.assignedTrack||r.role||'—')}</strong></div></div></div><div class="kitc-profile-section"><h3>🛠 Skills</h3><div class="kitc-profile-tags">${tag(skills,'🛠')}</div></div><div class="kitc-profile-section"><h3>❤️ Interests</h3><div class="kitc-profile-tags">${tag(interests,'❤️')}</div></div><div class="kitc-profile-section"><h3>📞 Contact</h3><div class="kitc-profile-contact">${r.email?`<div><small>Email</small><strong>${esc(r.email)}</strong></div>`:''}${r.phone?`<div><small>Phone</small><strong>${esc(r.phone)}</strong></div>`:''}${r.username?`<div><small>Username</small><strong>${esc(r.username)}</strong></div>`:''}${!r.email&&!r.phone&&!r.username?'<span class="kitc-profile-empty">No contact details</span>':''}</div></div><div class="kitc-profile-actions"><button class="button" type="button" data-profile-edit="${esc(r.id)}">✏️ Edit member</button></div></aside></div>`);const overlay=document.getElementById('kitcMemberProfile');overlay.querySelector('.kitc-profile-close').onclick=closeProfile;overlay.onclick=e=>{if(e.target===overlay)closeProfile()};overlay.querySelector('[data-profile-edit]').onclick=()=>{const memberId=overlay.querySelector('[data-profile-edit]').dataset.profileEdit;closeProfile();window.editMember?.(memberId)};document.addEventListener('keydown',profileEscape,{once:true});}
function closeProfile(){document.getElementById('kitcMemberProfile')?.remove()}
function profileEscape(e){if(e.key==='Escape')closeProfile()}
function inject(){if(document.getElementById('kitc-member-profile-styles'))return;const s=document.createElement('style');s.id='kitc-member-profile-styles';s.textContent=`.kitc-profile-overlay{position:fixed;inset:0;background:#0006;z-index:9999;display:flex;justify-content:flex-end}.kitc-profile-panel{width:min(430px,94vw);height:100%;overflow:auto;background:#fff;padding:28px;box-shadow:-10px 0 35px #0003;animation:kitcProfileIn .18s ease}.kitc-profile-close{float:right;border:0;background:#f2f4f7;border-radius:50%;width:36px;height:36px;font-size:24px;cursor:pointer}.kitc-profile-avatar{width:72px;height:72px;border-radius:20px;background:#eef2ff;display:grid;place-items:center;font-size:30px;font-weight:800;margin-top:8px}.kitc-profile-eyebrow{font-size:11px;font-weight:800;letter-spacing:.12em;color:#7b879a;margin-top:20px}.kitc-profile-panel h2{margin:5px 0 2px}.kitc-profile-id{margin:0 0 10px;color:#7b879a}.kitc-profile-status{display:inline-block;padding:5px 10px;border-radius:999px;background:#eaf8ef;font-size:12px;font-weight:700}.kitc-profile-section{border-top:1px solid #e8ebf0;margin-top:22px;padding-top:18px}.kitc-profile-section h3{margin:0 0 12px;font-size:14px}.kitc-profile-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.kitc-profile-grid div,.kitc-profile-contact div{display:flex;flex-direction:column;gap:3px}.kitc-profile-grid small,.kitc-profile-contact small{color:#8a94a6}.kitc-profile-tags{display:flex;gap:7px;flex-wrap:wrap}.kitc-profile-tag{padding:7px 10px;border-radius:999px;background:#f1f4f8;font-size:12px}.kitc-profile-empty{color:#8a94a6;font-size:13px}.kitc-profile-contact{display:grid;gap:10px}.kitc-profile-actions{margin-top:24px}.kitc-profile-actions .button{width:100%}@keyframes kitcProfileIn{from{transform:translateX(20px);opacity:.5}to{transform:none;opacity:1}}@media(max-width:600px){.kitc-profile-panel{padding:22px}}`;document.head.appendChild(s)}
function hook(){inject();document.addEventListener('click',e=>{const b=e.target.closest('[data-edit-member]');if(!b||!document.getElementById('content')?.contains(b))return;e.preventDefault();e.stopImmediatePropagation();openProfile(b.dataset.editMember)},true)}
window.addEventListener('DOMContentLoaded',hook);window.kitcOpenMemberProfile=openProfile;
})();