(()=>{'use strict';
const store=window.kitcData||{};
const map={members:{key:'members',type:'member',title:'Members',icon:'♙',desc:'Searchable member records, management roles and member history.',cols:['Name','Position','Class','Status']},meetings:{key:'meetings',type:'meeting',title:'Meetings',icon:'▣',desc:'Agendas, attendees, minutes, decisions and follow-up tasks.',cols:['Meeting','Date','Location','Next step']},tasks:{key:'tasks',type:'task',title:'Tasks',icon:'✓',desc:'Assignments, priorities, deadlines and completion tracking.',cols:['Task','Assigned to','Priority','Deadline','Status']},events:{key:'events',type:'event',title:'Programs & Events',icon:'★',desc:'Plan programs and preserve complete event records.',cols:['Event','Date','Venue','Status']}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const vals=(key,r)=>key==='members'?[r.name,r.role,r.class,r.status]:Array.isArray(r?.values)?r.values:[];
const getUSB=()=>window.kitcUsbHandle;
async function write(key){const root=getUSB();if(!root)throw Error('KITC USB is not connected');const dir=await root.getDirectoryHandle('database',{create:true});const file=await dir.getFileHandle(`${key}.json`,{create:true});const w=await file.createWritable();try{await w.write(JSON.stringify(store[key]||[],null,2))}finally{await w.close()}}
function notify(t){const el=document.getElementById('toast');if(!el)return;el.textContent=t;el.classList.add('show');clearTimeout(window.__moduleToast);window.__moduleToast=setTimeout(()=>el.classList.remove('show'),2400)}
const originalOpenAdd=window.openAdd;
window.openAdd=(type='member',id=null)=>originalOpenAdd(type==='members'?'member':type==='meetings'?'meeting':type==='tasks'?'task':type==='events'?'event':type,id);
function page(section){const m=map[section];if(!m)return null;const rows=Array.isArray(store[m.key])?store[m.key]:[];const body=rows.length?rows.map(r=>{const v=vals(m.key,r);return `<tr><td><input class="record-check module-check" type="checkbox" data-id="${esc(r.id)}"></td>${m.cols.map((_,i)=>`<td>${esc(v[i]??'')}</td>`).join('')}<td><button class="text-button" data-edit="${esc(r.id)}">Edit</button><button class="icon-button module-more" data-id="${esc(r.id)}" type="button">⋮</button></td></tr>`}).join(''):`<tr><td colspan="${m.cols.length+2}"><div class="empty-state"><div class="module-icon">${m.icon}</div><h3>No ${m.title} yet</h3><p>Your USB has no ${m.key}.json records loaded.</p><button class="button primary" data-add>＋ Add ${m.title.endsWith('s')?m.title.slice(0,-1):m.title}</button></div></td></tr>`;return `<div class="page-head"><div><div class="eyebrow">KITC • USB RECORDS</div><h1>${m.title}</h1><p>${m.desc}</p></div><button class="button primary" data-add>＋ Add ${m.title.endsWith('s')?m.title.slice(0,-1):m.title}</button></div><div class="table-card"><div class="record-toolbar"><label><input type="checkbox" id="moduleSelectAll"> Select all</label><span id="moduleSelected">0 selected</span><button class="button danger" id="moduleDelete" style="display:none">Delete selected</button></div><div class="table-wrap"><table class="table"><thead><tr><th></th>${m.cols.map(c=>`<th>${c}</th>`).join('')}<th>Actions</th></tr></thead><tbody>${body}</tbody></table></div></div>`}
function attach(section){const m=map[section];if(!m)return;document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>window.openAdd(m.type));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>window.openAdd(m.type,b.dataset.edit));const checks=[...document.querySelectorAll('.module-check')],all=document.getElementById('moduleSelectAll'),del=document.getElementById('moduleDelete'),count=document.getElementById('moduleSelected');const sync=()=>{const n=checks.filter(x=>x.checked).length;if(count)count.textContent=`${n} selected`;if(del)del.style.display=n?'inline-flex':'none';if(all)all.checked=checks.length>0&&n===checks.length};checks.forEach(c=>c.onchange=sync);if(all)all.onchange=()=>{checks.forEach(c=>c.checked=all.checked);sync()};if(del)del.onclick=async()=>{const ids=new Set(checks.filter(c=>c.checked).map(c=>c.dataset.id));if(!ids.size||!confirm(`Delete ${ids.size} selected record${ids.size>1?'s':''}?`))return;store[m.key]=(store[m.key]||[]).filter(r=>!ids.has(String(r.id)));try{await write(m.key);window.render(section);notify('Selected records deleted from USB ✓')}catch(e){notify(`USB save failed: ${e.message}`)}};document.querySelectorAll('.module-more').forEach(b=>b.onclick=()=>{document.querySelector('.module-menu')?.remove();const menu=document.createElement('div');menu.className='record-menu module-menu';menu.innerHTML='<button>✏️ Edit</button><button>🗑️ Delete</button>';Object.assign(menu.style,{position:'fixed',zIndex:10000});const r=b.getBoundingClientRect();menu.style.left=Math.min(r.left,window.innerWidth-170)+'px';menu.style.top=r.bottom+4+'px';menu.children[0].onclick=()=>{menu.remove();window.openAdd(m.type,b.dataset.id)};menu.children[1].onclick=async()=>{menu.remove();if(!confirm('Delete this record?'))return;store[m.key]=(store[m.key]||[]).filter(x=>String(x.id)!==String(b.dataset.id));try{await write(m.key);window.render(section);notify('Record deleted from USB ✓')}catch(e){notify(`USB save failed: ${e.message}`)}};document.body.appendChild(menu)});}
const oldRender=window.render;
window.render=(section='dashboard')=>{if(map[section]){try{document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.section===section));const c=document.getElementById('content');c.innerHTML=page(section);attach(section)}catch(e){console.error(e);document.getElementById('content').innerHTML=`<div class="panel"><h2>Unable to open ${esc(map[section].title)}</h2><p>${esc(e.message)}</p></div>`}}else oldRender(section)};
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>{if(map[b.dataset.section])setTimeout(()=>window.render(b.dataset.section),0)}));
const style=document.createElement('style');style.textContent='.empty-state{text-align:center;padding:48px 20px}.empty-state .module-icon{margin:0 auto 12px}.table-wrap{overflow:auto}.module-menu{position:fixed;z-index:10000;min-width:150px;padding:4px;border:1px solid rgba(255,255,255,.08);border-radius:10px;background:rgba(17,16,15,.92);box-shadow:0 16px 40px rgba(0,0,0,.35);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px)}.module-menu button{display:block;width:100%;border:0;background:transparent;color:rgba(255,255,255,.9);text-align:left;padding:9px 11px;border-radius:7px;cursor:pointer}.module-menu button:hover{background:rgba(255,255,255,.08)}';document.head.appendChild(style);
})();