(()=>{'use strict';
const S=window.kitcData||{};window.kitcData=S;const SUITE_KEYS=['followups','decisions','journal','letters','timeline','meeting_templates'];SUITE_KEYS.forEach(k=>{if(!Array.isArray(S[k]))S[k]=[]});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const id=()=>window.crypto?.randomUUID?window.crypto.randomUUID():Date.now()+'-'+Math.random().toString(36).slice(2);
function persist(){if(typeof window.kitcPersist==='function'&&!window.kitcPersist())toast('Could not save changes on this device')}
function toast(t){const e=document.getElementById('toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(window.__suiteToast);window.__suiteToast=setTimeout(()=>e.classList.remove('show'),2400)}
function vals(k,r){if(k==='members')return[r.name,r.role,r.class,r.status];return Array.isArray(r?.values)?r.values:[]}
function rows(k){return Array.isArray(S[k])?S[k]:[]}
function head(title,desc){return`<div class="page-head"><div><div class="eyebrow">KITC • SECRETARY DESK</div><h1>${esc(title)}</h1><p>${esc(desc)}</p></div></div>`}
const modules=[['suite-home','⌂','Secretary Home'],['followups','↻','Follow-ups'],['decisions','◈','Decision Register'],['journal','✎','Secretary Journal'],['timeline','◷','Activity Timeline'],['letters','▤','Official Letters'],['meeting_templates','▣','Meeting Templates']];
function injectNav(){const nav=document.querySelector('.nav');if(!nav||nav.dataset.suite)return;nav.dataset.suite='1';const divider=document.createElement('div');divider.style.cssText='height:1px;background:rgba(255,255,255,.08);margin:12px 8px 7px';nav.appendChild(divider);modules.slice(1).forEach(([sec,ic,t])=>{const b=document.createElement('button');b.className='nav-item';b.dataset.section=sec;b.innerHTML=`${ic} <span>${t}</span>`;nav.appendChild(b)});nav.addEventListener('click',e=>{const b=e.target.closest('.nav-item');if(b&&modules.some(x=>x[0]===b.dataset.section)){e.preventDefault();window.render(b.dataset.section)}})}
function home(){const tasks=rows('tasks'),pending=tasks.filter(r=>vals('tasks',r)[4]!=='Completed').length,overdue=tasks.filter(r=>{const v=vals('tasks',r);return v[3]&&v[4]!=='Completed'&&new Date(v[3])<new Date()}).length;return`${head('Secretary Home','Read-only command center • ready to work without external devices')}<div class="stats"><div class="stat"><div class="stat-top">Pending Tasks</div><strong>${pending}</strong><span class="trend">${overdue} overdue</span></div><div class="stat"><div class="stat-top">Follow-ups</div><strong>${rows('followups').filter(x=>x.status!=='Done').length}</strong><span class="trend">Need attention</span></div><div class="stat"><div class="stat-top">Decisions</div><strong>${rows('decisions').length}</strong><span class="trend">Institutional record</span></div><div class="stat"><div class="stat-top">Journal Entries</div><strong>${rows('journal').length}</strong><span class="trend">Secretary history</span></div></div><div class="section-grid"><article class="module-card"><div class="module-icon">↗</div><h3>Handover Package</h3><p>Download a complete JSON handover package for the next Secretary.</p><button class="button" style="margin-top:14px" onclick="suiteHandover()">↗ Download handover</button></article></div>`}
function listPage(key,title,desc,cols){const rs=rows(key);return`${head(title,desc)}<div class="table-card"><div class="table-wrap"><table class="table"><thead><tr>${cols.map(c=>`<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${rs.map(r=>{const v=r.values||[];return`<tr>${cols.map((_,i)=>`<td>${esc(v[i]||'')}</td>`).join('')}</tr>`}).join('')||`<tr><td colspan="${cols.length}"><div class="empty-state"><h3>No records yet</h3><p>This section is empty right now. Records will appear here when available.</p></div></td></tr>`}</tbody></table></div></div>`}
function decisions(){return listPage('decisions','Decision Register','A permanent read-only record of what KITC decided and who owns the next step.',['Decision','Meeting / date','Responsible','Deadline','Status'])}
function followups(){return listPage('followups','Follow-up Tracker','Read-only people, subjects, dates and outstanding replies.',['Person / team','Subject','Next follow-up','Status','Notes'])}
function journal(){return listPage('journal','Secretary Journal','A read-only chronological record of Secretary work.',['Date','Title','What happened','Next action'])}
function timeline(){return`${head('Activity Timeline','A chronological audit-style view of Secretary activity.')}<div class="panel"><div class="list">${rows('timeline').slice().reverse().map(x=>`<div class="list-row"><div><strong>${esc(x.title)}</strong><small>${esc(x.date)} • ${esc(x.note)}</small></div></div>`).join('')||'<div class="empty-state">No activity yet.</div>'}</div></div>`}
function letters(){return`${head('Official Letter Generator','Read-only saved letters. Export remains available.')}<div class="documents-grid">${rows('letters').map(r=>`<article class="document-card"><div class="document-info"><div class="document-name-row"><strong class="document-name">${esc(r.values?.[1]||'Untitled')}</strong></div><div class="document-category">${esc(r.values?.[2]||'')} • ${esc(r.status||'Draft')}</div><p>To: ${esc(r.values?.[0]||'')}</p><button class="button" onclick="suiteLetterText('${esc(r.id)}')">View / export</button></div></article>`).join('')||'<div class="document-empty"><h3>No letters yet</h3><p>No saved letters are available yet.</p></div>'}</div>`}
function downloadText(filename,text,type='text/plain'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function templates(){return listPage('meeting_templates','Meeting Templates','Read-only reusable structures for agenda, minutes and action items.',['Template','Agenda','Minutes checklist','Default action items'])}
function suiteLetterText(rid){const r=rows('letters').find(x=>x.id===rid);if(!r)return;const v=r.values||[];const text=`KASTURI INFORMATION & TECHNOLOGY CLUB (KITC)\n\nDate: ${v[2]||''}\nTo: ${v[0]||''}\nSubject: ${v[1]||''}\n\n${v[3]||''}\n\nRegards,\nSecretary\nKITC`;downloadText(`${(v[1]||'KITC-letter').replace(/[^a-z0-9]+/gi,'-')}.txt`,text);toast('Letter downloaded successfully ✓')}
function suiteHandover(){downloadText(`kitc-handover-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(S,null,2),'application/json');toast('Complete Secretary handover downloaded ✓')}
function suiteReport(name){const data={generated:new Date().toISOString(),report:name,members:rows('members').length,meetings:rows('meetings').length,tasks:rows('tasks').length,events:rows('events').length,attendance:rows('attendance').length,documents:rows('documents').length,followups:rows('followups').length,decisions:rows('decisions').length};downloadText(name.replace(/[^a-z0-9]+/gi,'-').toLowerCase()+'.json',JSON.stringify(data,null,2),'application/json');toast(name+' downloaded successfully ✓')}
function reportPage(){return`${head('Report Builder','Generate reusable Secretary reports from current workspace records.')}<div class="section-grid">${['Monthly Activity Report','Meeting & Decision Report','Pending Task Report','Event History Report','Attendance Report','Annual Secretary Report'].map(x=>`<article class="module-card"><div class="module-icon">▥</div><h3>${esc(x)}</h3><p>Build a JSON report snapshot from current records.</p><button class="button primary" onclick="suiteReport('${esc(x)}')">Download report</button></article>`).join('')}</div>`}
function suiteRender(section){injectNav();document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.section===section));window.KITC_SUITE_SECTION=section;const c=document.getElementById('content');if(!c)return;if(section==='suite-home')c.innerHTML=home();else if(section==='followups')c.innerHTML=followups();else if(section==='decisions')c.innerHTML=decisions();else if(section==='journal')c.innerHTML=journal();else if(section==='timeline')c.innerHTML=timeline();else if(section==='letters')c.innerHTML=letters();else if(section==='meeting_templates')c.innerHTML=templates();else if(section==='reports')c.innerHTML=reportPage();c.setAttribute('data-kitc-rendered','true')}
const baseRender=window.render;window.render=(section='dashboard')=>{if(section==='dashboard'){injectNav();baseRender(section);return}if(['followups','decisions','journal','timeline','letters','meeting_templates','reports'].includes(section))suiteRender(section);else baseRender(section)};
window.suiteRender=suiteRender;window.suiteHandover=suiteHandover;window.suiteReport=suiteReport;window.suiteLetterText=suiteLetterText;
function boot(){injectNav();const style=document.createElement('style');style.textContent='.suite-home{display:block}.documents-grid{grid-template-columns:repeat(3,minmax(0,1fr))}@media(max-width:900px){.documents-grid{grid-template-columns:1fr 1fr}}@media(max-width:620px){.documents-grid{grid-template-columns:1fr}}';document.head.appendChild(style)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
