(()=>{'use strict';
const S=window.kitcData||{};window.kitcData=S;['followups','decisions','journal','letters','timeline','meeting_templates'].forEach(k=>{if(!Array.isArray(S[k]))S[k]=[]});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const id=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(36).slice(2);
const root=()=>window.kitcUsbHandle;
async function db(){if(!root())throw Error('Connect the KITC USB first');return root().getDirectoryHandle('database',{create:true})}
async function save(k){const d=await db(),f=await d.getFileHandle(k+'.json',{create:true}),w=await f.createWritable();try{await w.write(JSON.stringify(S[k]||[],null,2))}finally{await w.close()}}
async function saveAll(){for(const k of Object.keys(S))if(Array.isArray(S[k])&&['members','meetings','tasks','events','attendance','issues','documents','followups','decisions','journal','letters','timeline','meeting_templates'].includes(k))await save(k)}
function toast(t){const e=document.getElementById('toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(window.__suiteToast);window.__suiteToast=setTimeout(()=>e.classList.remove('show'),2400)}
function vals(k,r){if(k==='members')return[r.name,r.role,r.class,r.status];return Array.isArray(r?.values)?r.values:[]}
function rows(k){return Array.isArray(S[k])?S[k]:[]}
function pageHead(label,title,desc,action='＋ Add',fn='suiteAdd()'){return `<div class="page-head"><div><div class="eyebrow">KITC • SECRETARY DESK</div><h1>${esc(title)}</h1><p>${esc(desc)}</p></div><button class="button primary" onclick="${fn}">${esc(action)}</button></div>`}
const modules=[['suite-home','⌂','Secretary Home'],['followups','↻','Follow-ups'],['decisions','◈','Decision Register'],['journal','✎','Secretary Journal'],['timeline','◷','Activity Timeline'],['letters','▤','Official Letters'],['meeting_templates','▣','Meeting Templates']];
function injectNav(){const nav=document.querySelector('.nav');if(!nav||nav.dataset.suite)return;nav.dataset.suite='1';const divider=document.createElement('div');divider.style.cssText='height:1px;background:rgba(255,255,255,.08);margin:12px 8px 7px';nav.appendChild(divider);modules.slice(1).forEach(([sec,ic,t])=>{const b=document.createElement('button');b.className='nav-item';b.dataset.section=sec;b.innerHTML=`${ic} <span>${t}</span>`;nav.appendChild(b)});nav.addEventListener('click',e=>{const b=e.target.closest('.nav-item');if(b&&modules.some(x=>x[0]===b.dataset.section)){e.preventDefault();window.render(b.dataset.section)}})}
function card(title,text,action,fn){return `<article class="module-card"><div class="module-icon">${action[0]}</div><h3>${esc(title)}</h3><p>${esc(text)}</p><button class="button" style="margin-top:14px" onclick="${fn}">${esc(action.slice(1))}</button></article>`}
function home(){const tasks=rows('tasks'),pending=tasks.filter(r=>{const v=vals('tasks',r);return v[4]!=='Completed'}).length,overdue=tasks.filter(r=>{const v=vals('tasks',r);return v[3]&&v[4]!=='Completed'&&new Date(v[3])<new Date()}).length;return `${pageHead('Secretary • 2026–27','Good afternoon, Secretary 👋','Your private command center • USB is the source of truth','＋ Quick Add','suiteAdd()')}<div class="stats"><div class="stat"><div class="stat-top">Pending Tasks</div><strong>${pending}</strong><span class="trend">${overdue} overdue</span></div><div class="stat"><div class="stat-top">Follow-ups</div><strong>${rows('followups').filter(x=>x.status!=='Done').length}</strong><span class="trend">Need attention</span></div><div class="stat"><div class="stat-top">Decisions</div><strong>${rows('decisions').length}</strong><span class="trend">Institutional record</span></div><div class="stat"><div class="stat-top">Journal Entries</div><strong>${rows('journal').length}</strong><span class="trend">Secretary history</span></div></div><div class="section-grid">${card('Follow-ups','Never forget who you need to contact or chase.','↻ Add follow-up','suiteAdd(\'followup\')')}${card('Decision Register','Record decisions with owner, deadline and status.','◈ Add decision','suiteAdd(\'decision\')')}${card('Secretary Journal','Keep a private chronological work log.','✎ Add entry','suiteAdd(\'journal\')')}${card('Official Letter Generator','Create standardized letters and save them to USB.','▤ Create letter','suiteAdd(\'letter\')')}${card('Meeting Workflow','Reusable agenda → minutes → decisions → actions templates.','▣ New template','suiteAdd(\'template\')')}${card('Handover Package','Copy the complete Secretary record into a dated USB handover folder.','↗ Build handover','suiteHandover()')}</div><div class="grid-2"><section class="panel"><div class="panel-head"><h2>Upcoming / Recent</h2><span class="muted">Secretary view</span></div><div class="list">${rows('events').slice(0,5).map(r=>{const v=vals('events',r);return `<div class="list-row"><div><strong>${esc(v[0]||'Event')}</strong><small>${esc(v[1]||'')} • ${esc(v[2]||'')}</small></div><span class="pill">${esc(v[3]||'Planned')}</span></div>`}).join('')||'<div class="empty-state">No events yet.</div>'}</div></section><section class="panel"><div class="panel-head"><h2>Latest activity</h2><span class="muted">USB timeline</span></div><div class="list">${rows('timeline').slice(-5).reverse().map(x=>`<div class="list-row"><div><strong>${esc(x.title)}</strong><small>${esc(x.date)} • ${esc(x.note)}</small></div></div>`).join('')||'<div class="empty-state">Your activity will appear here.</div>'}</div></section></div>`}
const defs={followup:{key:'followups',title:'Follow-up',fields:['Person / team','Subject','Next follow-up date','Status','Notes']},decision:{key:'decisions',title:'Decision',fields:['Decision','Meeting / date','Responsible person','Deadline','Status']},journal:{key:'journal',title:'Journal entry',fields:['Date','Title','What happened','Next action']},letter:{key:'letters',title:'Official letter',fields:['Recipient','Subject','Date','Body']},template:{key:'meeting_templates',title:'Meeting template',fields:['Template name','Agenda','Minutes checklist','Default action items']}};
function suiteAdd(type='followup',editId=null){const d=defs[type];if(!d)return;const old=editId?rows(d.key).find(x=>x.id===editId):null;document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="suiteModal"><div class="modal"><button class="modal-close" onclick="document.getElementById('suiteModal')?.remove()">×</button><div class="eyebrow">KITC • USB</div><h2>${old?'Edit ':'Add '}${esc(d.title)}</h2><form id="suiteForm">${d.fields.map((f,i)=>`<label>${esc(f)}${f==='Body'||f.includes('checklist')||f==='Agenda'||f==='Notes'||f==='What happened'||f==='Next action'?`<textarea name="f${i}" rows="4">${esc(old?.values?.[i]||'')}</textarea>`:`<input name="f${i}" value="${esc(old?.values?.[i]||'')}" required>`}</label>`).join('')}<button class="button primary">Save to USB</button></form></div></div>`);document.getElementById('suiteForm').onsubmit=async e=>{e.preventDefault();const v=[...new FormData(e.target).values()];const r={id:old?.id||id(),values:v,status:v[3]||'Pending'};if(old)S[d.key][S[d.key].findIndex(x=>x.id===old.id)]=r;else S[d.key].push(r);if(type==='letter')r.status='Draft';try{await save(d.key);document.getElementById('suiteModal')?.remove();suiteRender(d.key);addTimeline(d.title,'Created/updated record');toast(d.title+' saved to USB ✓')}catch(err){toast('USB save failed: '+err.message)}}}
async function addTimeline(title,note){const r={id:id(),date:new Date().toISOString().slice(0,10),title,note};S.timeline.push(r);try{await save('timeline')}catch{}}
function listPage(key,title,desc,type,cols){const rs=rows(key);return `${pageHead('Secretary Desk',title,desc,`＋ Add ${type}`,`suiteAdd('${type}')`)}<div class="table-card"><div class="table-wrap"><table class="table"><thead><tr>${cols.map(c=>`<th>${esc(c)}</th>`).join('')}<th>Actions</th></tr></thead><tbody>${rs.map(r=>{const v=r.values||[];return `<tr>${cols.map((_,i)=>`<td>${esc(v[i]||'')}</td>`).join('')}<td><button class="text-button" onclick="suiteAdd('${type}','${esc(r.id)}')">Edit</button></td></tr>`}).join('')||`<tr><td colspan="${cols.length+1}"><div class="empty-state"><h3>No records yet</h3><p>Everything you add here is written to the KITC USB database.</p></div></td></tr>`}</tbody></table></div></div>`}
function decisions(){return listPage('decisions','Decision Register','A permanent record of what KITC decided and who owns the next step.','decision',['Decision','Meeting / date','Responsible','Deadline','Status'])}
function followups(){return listPage('followups','Follow-up Tracker','Track people, subjects, dates and outstanding replies.','followup',['Person / team','Subject','Next follow-up','Status','Notes'])}
function journal(){return listPage('journal','Secretary Journal','A private chronological record of your Secretary work.','journal',['Date','Title','What happened','Next action'])}
function timeline(){return `${pageHead('History','Activity Timeline','A chronological audit-style view of your Secretary activity.','Refresh','suiteRender(\'timeline\')')}<div class="panel"><div class="list">${rows('timeline').slice().reverse().map(x=>`<div class="list-row"><div><strong>${esc(x.title)}</strong><small>${esc(x.date)} • ${esc(x.note)}</small></div></div>`).join('')||'<div class="empty-state">No activity yet.</div>'}</div></div>`}
function letters(){return `${pageHead('Correspondence','Official Letter Generator','Create standardized official letters and save the editable record to USB.','＋ New letter',"suiteAdd('letter')")}<div class="documents-grid">${rows('letters').map(r=>`<article class="document-card"><div class="document-info"><div class="document-name-row"><strong class="document-name">${esc(r.values?.[1]||'Untitled')}</strong></div><div class="document-category">${esc(r.values?.[2]||'')} • ${esc(r.status||'Draft')}</div><p>To: ${esc(r.values?.[0]||'')}</p><button class="button" onclick="suiteLetterText('${esc(r.id)}')">View / export</button></div></article>`).join('')||'<div class="document-empty"><h3>No letters yet</h3><p>Create your first official letter.</p></div>'}</div>`}
function templates(){return listPage('meeting_templates','Meeting Templates','Reusable structures for agenda, minutes and action items.','template',['Template','Agenda','Minutes checklist','Default action items'])}
async function suiteLetterText(rid){const r=rows('letters').find(x=>x.id===rid);if(!r)return;const v=r.values||[];const text=`KASTURI INFORMATION & TECHNOLOGY CLUB (KITC)\n\nDate: ${v[2]||''}\nTo: ${v[0]||''}\nSubject: ${v[1]||''}\n\n${v[3]||''}\n\nRegards,\nSecretary\nKITC`;const d=await db(),dir=await d.getDirectoryHandle('letters',{create:true}),f=await dir.getFileHandle(`${(v[1]||'KITC-letter').replace(/[^a-z0-9]+/gi,'-')}.txt`,{create:true}),w=await f.createWritable();await w.write(text);await w.close();toast('Letter exported to USB ✓')}
async function suiteHandover(){try{const r=root();if(!r)throw Error('Connect the KITC USB first');const stamp=new Date().toISOString().slice(0,10),h=await r.getDirectoryHandle('handover-'+stamp,{create:true});for(const k of ['members','meetings','tasks','events','attendance','issues','documents','followups','decisions','journal','letters','timeline','meeting_templates']){const f=await h.getFileHandle(k+'.json',{create:true}),w=await f.createWritable();await w.write(JSON.stringify(rows(k),null,2));await w.close()}toast('Complete Secretary handover package saved to USB ✓')}catch(e){toast('Handover failed: '+e.message)}}
async function suiteReport(name){try{const r=root();if(!r)throw Error('Connect the KITC USB first');const h=await r.getDirectoryHandle('reports',{create:true}),data={generated:new Date().toISOString(),report:name,members:rows('members').length,meetings:rows('meetings').length,tasks:rows('tasks').length,events:rows('events').length,attendance:rows('attendance').length,documents:rows('documents').length,followups:rows('followups').length,decisions:rows('decisions').length};const f=await h.getFileHandle(name.replace(/[^a-z0-9]+/gi,'-')+'.json',{create:true}),w=await f.createWritable();await w.write(JSON.stringify(data,null,2));await w.close();toast(name+' saved to USB ✓')}catch(e){toast('Report failed: '+e.message)}}
function reportPage(){return `${pageHead('Analytics','Report Builder','Generate reusable Secretary reports from records stored on the USB.','Annual report','suiteReport(\'Annual Secretary Report\')')}<div class="section-grid">${['Monthly Activity Report','Meeting & Decision Report','Pending Task Report','Event History Report','Attendance Report','Annual Secretary Report'].map(x=>`<article class="module-card"><div class="module-icon">▥</div><h3>${esc(x)}</h3><p>Build a JSON report snapshot from current USB records.</p><button class="button primary" onclick="suiteReport('${esc(x)}')">Save to USB</button></article>`).join('')}</div>`}
function suiteRender(section){injectNav();document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.section===section));window.KITC_SUITE_SECTION=section;const c=document.getElementById('content');if(section==='suite-home')c.innerHTML=home();else if(section==='followups')c.innerHTML=followups();else if(section==='decisions')c.innerHTML=decisions();else if(section==='journal')c.innerHTML=journal();else if(section==='timeline')c.innerHTML=timeline();else if(section==='letters')c.innerHTML=letters();else if(section==='meeting_templates')c.innerHTML=templates();else if(section==='reports')c.innerHTML=reportPage();}
const baseRender=window.render;window.render=(section='dashboard')=>{if(section==='dashboard'){injectNav();baseRender(section);return}if(['followups','decisions','journal','timeline','letters','meeting_templates'].includes(section))suiteRender(section);else baseRender(section)};
window.suiteAdd=suiteAdd;window.suiteRender=suiteRender;window.suiteHandover=suiteHandover;window.suiteReport=suiteReport;window.suiteLetterText=suiteLetterText;
function boot(){injectNav();const style=document.createElement('style');style.textContent='.suite-home{display:block}.module-card .button{font-size:10px}.documents-grid{grid-template-columns:repeat(3,minmax(0,1fr))}@media(max-width:900px){.documents-grid{grid-template-columns:1fr 1fr}}@media(max-width:620px){.documents-grid{grid-template-columns:1fr}}';document.head.appendChild(style)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();